accounts/urls.py
from django.urls import path
# Viewsモジュールをインポート
from . import views

# viewsをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるようにアプリ名を登録
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # http://ホスト名/signup/へのアクセスに対して
    # viewsモジュールのSignupViewをインスタンス化する
    path('signup/', views.SignUpView.as_view(), name='signup'),
    # サインアップ完了ページのビューの呼び出し
    # http://ホスト名/signup_success/へのアクセスに対して
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',views.SignUpSuccessView.as_view(), name='signup_success'),

    # ログインページの表示
    # http:///ホスト名/signup へのアクセスに対して
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
        #  ログイン用のテンプレートフォームをレンダリング
        auth_views.LoginView.as_view(template_name='login.html'),
        name='login'
        ),

    # ログアウトを実行
    # http:///ホスト名/logout/ へのアクセスに対して
    # django.contrib.auth.views.LogoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
        #  ログイン用のテンプレートフォームをレンダリング
        auth_views.LogoutView.as_view(template_name='logout.html'),
        name='logout'
        ),
]

kouka2/urls.py
from django.contrib import admin
from django.urls import path,include


# auth.viwesをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views
# settingを追加
from django.conf import settings
# staticを追加
from django.conf.urls.static import static

# URLパターンを登録するための変数


urlpatterns = [
    path('admin/', admin.site.urls),

    #https(S)://ホスト名/へのアクセスはblogappの
    #URLcong(urls.py)を呼び出す
    path('',include('kouka2app.urls')),

        # photo.urlへのURLパターン
    # path('',include('photo.urls')),

    # accounts.urlへのURLパターン
    path('',include('accounts.urls')),

    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name = "password_reset.html"),
         name = 'password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name = "password_reset_sent.html"),
         name = 'password_reset_done'),

    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name ="password_reset_form.html"),
             name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name ="password_reset_done.html"),
         name = 'password_reset_complete'),


]

# urlpatternsにmediaフォルダーのURLパターンを追加
urlpatterns += static(
   # MEDIA_URL = '/media/'
  settings.MEDIA_URL,
  # MEDIA_ROOTにリダイレクト
  document_root=settings.MEDIA_ROOT
  )

kouka2app/urls.py
from django.urls import path
from . import views

#URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = 'kouka2app'

#URLパターンを登録するためのリスト
urlpatterns = [
    #http(s)//ホスト名/以下パスが''無しの場合
    #viwsモジュールのIndexviweを実行
    #URLパターン名は’Index’
    path('',views.IndexView.as_view(), name='index'),

        # 写真投稿ページへのアクセスはviewsモジュールのCreatePhotoViewを実行
    path('post/', views.CreatePhotoView.as_view(), name='post'),

    # 投稿完了ページへのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),
    
    # カテゴリ一覧ページ
    # photos/<Categorysテーブルのid値>にマッチング
    # <int:category>は辞書{category:id(int)}としてcategoryViewに渡される
        path('photos/<int:category>',
          views.CategoryView.as_view(),
          name = 'photos_cat'
          ),

    # ユーザー投稿の一覧ページ
    # photos/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user:id値(int)}としてCategoryViewに渡される
    path('user-list/<int:user>',views.UserView.as_view(),
         name = 'user_list'
         ),

    # 詳細ページ
    # photos/<PhotoPostテーブルのid値>にマッチング
    # <int:pk>は辞書{pk:id値(int)}としてDetailViewに渡される
    path('photo-detail/<int:pk>',views.DetailView.as_view(),
         name = 'photo_detail'
         ),

    # マイページ
    # mypage/へのアクセスはMypaggeViewを実行
    path('mypage/',views.MypageView.as_view(),
         name = 'mypage'
         ),
    
    # 投稿写真の削除
    # photo/<photo postテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk:id値(int)}としてDetailViewに渡される
    path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name = 'photo_delete'
         ),

     # photogalleryトップ
    path('photogallery/',
         views.PhotogalleryView.as_view(),
         name = 'photogallery'
         ),


    #リクエストされたURLが「blob_detail1/レコードid/」の場合
    #viewモジュールのBlogDetailを実行
    #URLパターン名は'Blog_detail'
    path(
        #詳細ページのURLは｢blog-detail/レコードのid/」
        'blog-detail/<int:pk>/',
        #viewモジュールのBlogDetailを実行
        views.BlogDetail.as_view(),
        #URLパターンの名前を'blog_detail'にする
        name='blog_detail'
        ),
    #festivalカテゴリーの一覧ページのURLパターン
    path(
        #festivalカテゴリーの一覧ページのURL｢festival-list｣
        'festival-list/',
        #viewsモジュールのBlogDetailを実行
        views.FestivalView.as_view(),
        #URLパターンの名前を'science_list'にする
        name='festival_list'
        ),
    #schoolカテゴリーの一覧ページのURLパターン
    path(
        #schoolカテゴリーの一覧ページのURL｢school-list｣
        'school-list/',
        #viewsモジュールのSchoolViewを実行
        views.SchoolView.as_view(),
        #URLパターンの名前を'school_list'にする
        name='school_list'
        ),
    #iventカテゴリーの一覧ページのURLパターン
    path(
        #iventカテゴリーの一覧ページのURL｢ivent-list｣
        '-list/',
        #viewsモジュールのIventViewを実行
        views.IventView.as_view(),
        #URLパターンの名前を'ivent_list'にする
        name='ivent_list'
        ),  

    #cleaningカテゴリーの一覧ページのURLパターン
    path(
        #cleaningカテゴリーの一覧ページのURL｢cleaning-list｣
        'cleaning-list/',
        #viewsモジュールのMusicViewを実行
        views.CleaningView.as_view(),
        #URLパターンの名前を'cleaning_list'にする
        name='cleaning_list'
        ),  

     #safetyカテゴリーの一覧ページのURLパターン
    path(
        #safetyカテゴリーの一覧ページのURL｢safety-list｣
        'safety-list/',
        #viewsモジュールのSafetyViewを実行
        views.SafetyView.as_view(),
        #URLパターンの名前を'safety_list'にする
        name='safety_list'
        ),  

    #othersカテゴリーの一覧ページのURLパターン
    path(
        #othersカテゴリーの一覧ページのURL｢others-list｣
        'others-list/',
        #viewsモジュールのOthersViewを実行
        views.OthersView.as_view(),
        #URLパターンの名前を'others_list'にする
        name='others_list'
        ),  

    #カレンダーページのURLパターン
    path(
        #カレンダーページのURL｢calender｣
        'calender',
        #viewsモジュールのCalenderViewを実行
        views.CalenderView.as_view(),
        #URLパターンの名前を'calender'にする
        name='calender'
        ),  


]


kouka2app/forms.py
from django.forms import ModelForm
from .models import PhotoPost

# ModelFormを継承したPhotoPostFormクラスを定義
class PhotoPostForm(ModelForm):
    # ModelFormのサブクラス

    class Meta:
        # ModelFormのインナークラス

        # Attributes:
            # model:モデルのクラス
            # fields:フォームで使用するモデルのフィールドを指定
        
        model = PhotoPost
        fields = ['category','title','comment','image1','image2','image3']

kouka2app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView
# from django.views.generic import DetailView
from django.views.generic import DetailView
# django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
# django.urlからreverse_lazyをインポート
from django.urls import reverse_lazy
# formモジュールからPhotoPostFormをインポート
from .forms import PhotoPostForm
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requuredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからPhotopostをインポート
from .models import PhotoPost
# django.views.genericからDeleteViewをインポート
from django.views.generic import DeleteView


# モデルBlogPostをインポート
from .models import BlogPost

class IndexView(ListView):
    #トップページのビュー
    #投稿記事を一覧表示するのでListViweを継承する

    #Attributes:
        #template_name:レンダリングするテンプレート
        #context_object_name:object_listキーの別名を設定
        #queryset:データベースのクエリ

    model = BlogPost

    #index.htmlをレンダリングする
    template_name ='index.html'
    #object_listキーの別名を設定
    context_object_name = 'orderby_records'
    #モデルBlogPostのオブジェクトにorder_by()を定期用して
    #BlogPostのレコードを登校日の降順で並べ替える
    queryset = BlogPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数を設定
    paginate_by = 4


    # デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限られる
    # ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    # 写真投稿のページのビュー

    # PhotoPostFormで定義されているモデルとフィールドと連携して
    # 投稿データをデータベースに登録する

    # Attributes:
        # from_class:モデルとフィールドが登録されたフォームクラス
        # template_name:レンダリングするテンプレート
        # success_url:データベースへの登録完了後のリダイレクト先

    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = "post_photo.html"
    # フォームデータ登録後のリダイレクト先
    success_url = reverse_lazy('kouka2app:post_done')

    def form_valid(self, form):
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してもでるのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)
    
class PostSuccessView(TemplateView):
    # 投稿完了ページのビュー

    # Attributes:
        # template_name:レンダリングするテンプレート
    # index.htmlをレンダリングする
    template_name ='post_success.html'


# カテゴリページのビュー
class CategoryView(ListView):
    # Attributes:
        # template_name:レンダリングするテンプレート
        # pagination_by:1ページに表示するレコードの件数
    
    # index.htmlをレンダリングする
    template_name ='photogallery.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    # クエリを実行する
    def get_queryset(self):
        # self.kwargsの取得が必要なため、クラス変数quertsetではなく、
        # get_queryset()のオーバーライドによりクエリを実行する

        # Returns:
            # クエリによって取得されたレコード
        # self.kwargsでキーワードの辞書を取得し、
        # categoryキーの値（categoryテーブルのid）を取得
        category_id = self.kwargs['category']
        # filter(フィールド名＝id)で絞り込む、order_byで投稿日順に並び替える
        categories = PhotoPost.objects.filter(
            category=category_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories

# ユーザー投稿一覧ページのビュー
class UserView(ListView):
    # Attributes:
        # template_name:レンダリングするテンプレート
        # pagination_by:1ページに表示するレコードの件数
    template_name = 'photogallery.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    # クエリを実行する
    def get_queryset(self):
        # selfパラメータで自分自身のオブジェクト（UserViewオブジェクト）を取得
        # self.kwargsの取得が必要なため、クラス変数quertsetではなく、
        # ユーザーID値を取得するためget_queryset()のオーバーライドによりクエリを実行する

        # Returns: クエリによって取得されたレコード
        
        # self.kwargsでキーワードの辞書を取得し、
        #userキーの値（ユーザーテーブルのid）を取得
        user_id = self.kwargs['user']
        # filter(フィールド名＝id)で絞り込む
        user_list = PhotoPost.objects.filter(
            user=user_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return user_list

# 詳細ページのビュー
class DetailView(DetailView):
    
    # 投稿記事の詳細を表示するのでDetailViewを継承する
    # Attributes:
        # template_name:レンダリングするテンプレート
        # model:モデルのクラス
    # post.htmlをレンダリングする
    template_name = 'detail.html'
    # クラス変数modelにモデルBlogPostを設定
    model = PhotoPost

# マイページのビュー
class MypageView(ListView):
    
    # Attributes:
        # template_name:レンダリングするテンプレート
        # pagination_by:1ページに表示するレコードの件数
    template_name = 'mypage.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    # クエリを実行する
    def get_queryset(self):
        # selfパラメータで自分自身のオブジェクト（UserViewオブジェクト）を取得
        # self.kwargsの取得が必要なため、クラス変数quertsetではなく、
        # get_queryset()のオーバーライドによりクエリを実行、自分自信のMypageViewオブジェクトを取得

        # Returns: クエリによって取得されたレコード
        
        # 現在ログインしているユーザー名はHttpRequest.userに格納されている
        #filter（userフィールド=userオブジェクト）で絞り込む
        queryset = PhotoPost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return queryset

# レコードの削除を行うビュー
class PhotoDeleteView(DeleteView):
    
    # Attributes:
        # model:モデル
        # template_name:レンダリングするテンプレート
        # pagination_by:1ページに表示するレコードの件数
        # success_url:削除完了後のリダイレクト先URL
    model = PhotoPost
    template_name = 'photo_delete.html'
    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('photo:mypage')
    
    def delete(self, request, *args, **kwargs):
        # レコードの削除を行う

        # Parameters:
        # self:PhotoDeleteViewオブジェクト
        # request:WSGIRequest(HttpRequest)オブジェクト
        # args:引数として渡される（dict)
        # kwargs:キーワードつきの辞書（dict)
        # {'pk':21}のようにレコードidが渡される

            # Returns:
                # HttpResponseRedirect(Success_url)を返して
                # success_urlにリダイレクト

                # スーパークラスのdelete()を実行
            return super().delete(request, *args, **kwargs)

class PhotogalleryView(ListView):
    #トップページのビュー
    #投稿記事を一覧表示するのでListViweを継承する

    #Attributes:
        #template_name:レンダリングするテンプレート
        #context_object_name:object_listキーの別名を設定
        #queryset:データベースのクエリ

    #photogallery.htmlをレンダリングする
    template_name ='photogallery.html'
    # モデルBlogPostのオブジェクトにorder_by()を適用して
    # 投稿日時の降順で並び替える
    queryset = PhotoPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 9

    # デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限られる
    # ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる


class BlogDetail(DetailView):
    #詳細のページ

    #投稿記事の詳細を表示するのでDetailViewを継承する
    #Attributes:
        #template_name:レンダリングするテンプレート
        #Model:モデルのクラス

    #post.htmlをレンダリングする
    template_name ='post.html'
    #クラス変数modelにBlogPostを設定
    model = BlogPost

class FestivalView(ListView):
    # festival:お祭りカテゴリの記事を一覧表示するビュー

    # festival_list.htmlをレンダリングする
    template_name ='festival_list.html'
    # クラス変数にmodelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'festival_records'
    # category='festival'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='festival').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

class SchoolView(ListView):
    # school:学校関連カテゴリの記事を一覧表示するビュー

    # school_list.htmlをレンダリングする
    template_name ='school_list.html'
    # クラス変数にmodelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'school_records'
    # category='school'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='school').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

class IventView(ListView):
    # ivent:イベントカテゴリの記事を一覧表示するビュー

    # ivent_list.htmlをレンダリングする
    template_name ='ivent_list.html'
    # クラス変数にmodelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'ivent_records'
    # category='ivent'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='ivent').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

class CleaningView(ListView):
    # cleaning:清掃活動カテゴリの記事を一覧表示するビュー

    # cleaning_list.htmlをレンダリングする
    template_name ='cleaning_list.html'
    # クラス変数にmodelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'cleaning_records'
    # category='cleaning'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='cleaning').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

class SafetyView(ListView):
    # safety:安心･安全カテゴリの記事を一覧表示するビュー

    # safety_list.htmlをレンダリングする
    template_name ='safety_list.html'
    # クラス変数にmodelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'safety_records'
    # category='safety'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='safety').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

class OthersView(ListView):
    # others:その他カテゴリの記事を一覧表示するビュー

    # others_list.htmlをレンダリングする
    template_name ='others_list.html'
    # クラス変数にmodelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'others_records'
    # category='others'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='others').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

# カレンダーページのビュー
class CalenderView(TemplateView):
    
    # Attributes:
    # template_name:レンダリングするテンプレート
    # googleカレンダーテンプレートをレンダリングする
    template_name = 'calender.html'

    # クエリを実行する
    def get_context_data(self,**kwargs):
        # コンテキストデータを取得する

kouka2app/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}{% endblock %}</title>

    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon"
          href={% static 'assets/favicon.ico' %} />


    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>   
      .navbar-dark {
        background-image: url('{% static "img/head.jpg" %}');
        background-size: cover;
         /* 画像のサイズを調整 */
        /* 他の背景設定（例えば、色や透明度）を追加できます */
      }
      .navbar-brand .text-secondary {
        font-size: 1.5em; /* テキストを1.5倍のサイズに設定（例） */
      }
      .navbar-brand .text-secondary {
        color: #535252 !important; /* テキストのカラーを濃い灰色に設定 */
      }

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

    

    </style>    
  </head>
  
  <body>
    <!-- ページのヘッダー -->
    <header>
      
      <!-- ナビゲーションバーのヘッダー -->
      <div class="navbar-dark">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-1">
                        <!-- トップページへのリンク-->
              <a href="{% url 'kouka2app:index' %}"
                class="navbar-brand d-flex align-items-center">
              <svg xmlns="http://www.w3.org/2000/svg"
                    width="20" height="20" fill="none"
                    stroke="#008000"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    aria-hidden="true"
                    class="me-2"
                    viewBox="0 0 24 24">
              <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
              <circle cx="12" cy="13" r="4"/></svg>
            <!-- リンクテキスト-->
            
            <strong class="text-secondary">白沢甲部子ども会 Blog･Photogallery</strong>
            </a>
            
              
              <!-- ヘッダーのタイトルと本文-->
              <!-- <h4 class="text-secondary">お気に入りを見つけよう！</h4> -->
              <p class="text-muted">
                 行事の様子はBlogでお知らせします。
                <br> 子ども会の行事で撮った写真は、ぜひ
                Photogalleryに投稿してください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-3 text-end">
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー -->
                {%if user.is_authenticated %}

                <!-- ログイン中のメニュー -->
                <li><a href="{% url 'kouka2app:mypage' %}"
                      class="text-secondary">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}"      
                      class="text-secondary">ログアウト</a></li>
                <li><a href="{% url 'password_reset' %}"    
                      class="text-secondary">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com"
                      class="text-secondary">Email me</a></li>
                {% else %}

                <!-- ログイン状態ではない場合のメニュー -->
                <li><a href="{% url 'accounts:signup' %}" 
                       class="text-secondary">サインアップ</a></li>
                       <li><a href="{% url 'accounts:login' %}"
                        class="text-secondary">ログイン</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-secondary">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
        </div>
      </div>
      <hr style="margin-top: 0;">
    </header>
    
    <!-- メインコンテンツ -->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む -->
      {% block contents %}{% endblock %}
    </main>
    
    <!-- フッター -->
    <footer class="text-muted py-3">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          白沢甲部こども会 &copy; Bootstrap</p>
        <!-- 2つ目の<p class="mb-0">は末尾の</p>まで削除-->
      </div>
    </footer>
    
    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script> 
    
    </script>
  </body>
</html>

kouka2app/templates/photos_title.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}


<!-- タイトルとナビゲーションボタン -->
  <section class="py-0 text-center container">
    <div class="row py-lg-2">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        <img class="mb-4"
             src={% static "img/logo.png" %}
             alt="" width="270"
             height="270">
        
        <p class="lead text-muted smaller-font">
          白沢甲部子ども会のブログです。
          行事のご案内や様子をお知らせします。</p>
        <p>
          <!-- ナビゲーションボタン -->
          
          {% if user.is_authenticated %}
          <!-- ログイン中のボタン -->
          <a href="{% url 'kouka2app:photogallery' %}"
            class="btn btn-primary my-2">Photogalleryへ</a>
          <a href="{% url 'kouka2app:post' %}"
            class="btn btn-primary my-2">photo投稿</a>
          <a href="{% url 'kouka2app:calender' %}"
            class="btn btn-primary my-2" style="background-color: rgb(37, 201, 37);">カレンダー</a>
          <a href="{% url 'accounts:logout' %}"
            class="btn btn-secondary my-2">ログアウト</a>
          
          {% else %}
          <!-- ログイン状態ではない場合のボタン -->
          <a href="{% url 'kouka2app:photogallery' %}"
          class="btn btn-primary my-2">Photogalleryへ</a>
          <a href="{% url 'accounts:signup' %}"
            class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}"
            class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}

                  </p>
        <style>
          /* テキストの色を指定 */
          .text-muted {
            color: #241616; /* 希望の色に変更 */
          }
        
          /* テキストのフォントサイズを調整 */
          .smaller-font {
            font-size: 1.1em; /* フォントサイズを調整 */
          }
        </style>
        
       
      </div>
    </div>
  </section>